<a href="https://colab.research.google.com/github/loppi-ru/0315/blob/main/%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B07_%D0%90%D1%85%D0%BC%D0%B0%D1%82%D0%BE%D0%B2%D0%B0%D0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

с клавиатуры вводится число, n - кол-во строк и столбцов матрицы. Реализуйте матрицу размером n на n элементов из подряд идущих чисел. Например, для числа 2 исходной матрицей будет
 [[1, 2],
 [3, 4]]
 После этого выведите полученную матрицу и ее определитель

In [11]:
import numpy as np

n = int(input("Введите размер матрицы n: "))

matrix = np.arange(1, n*n + 1).reshape(n, n)

print("Полученная матрица:")
print(matrix)

determinant = np.linalg.det(matrix)

print("Определитель матрицы:", determinant)


Введите размер матрицы n: 4
Полученная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Определитель матрицы: 0.0


дана таблица с данными об учениках и их успеваемости. Из таблички необходимо получить следующие данные:
1. по какому предмету самый высокий средний балл?
кто из учеников больше других преуспевает по всем предметам (имеет самый высокий балл)?
Исходная таблица:
[[ 'ФИО', 'Балл по программированию', 'Балл по ОБЖ', 'Балл по алгебре']
[ 'Петров', '78', '93', '61']
[ 'Иванов', '56', '67', '73']
[ 'Сидорова', '81', '75', '70']]

In [10]:
import pandas as pd

data = {
    'ФИО': ['Петров', 'Иванов', 'Сидорова'],
    'Балл по программированию': [78, 56, 81],
    'Балл по ОБЖ': [93, 67, 75],
    'Балл по алгебре': [61, 73, 70]
}

df = pd.DataFrame(data)

average_scores = df[['Балл по программированию', 'Балл по ОБЖ', 'Балл по алгебре']].mean()

highest_avg_subject = average_scores.idxmax()
highest_avg_score = average_scores.max()

df['Средний балл'] = df[['Балл по программированию', 'Балл по ОБЖ', 'Балл по алгебре']].mean(axis=1)
top_student = df.loc[df['Средний балл'].idxmax(), 'ФИО']
top_student_score = df['Средний балл'].max()

print("Самый высокий средний балл по предмету:", highest_avg_subject, "с баллом", highest_avg_score)
print("Ученик, который больше других преуспевает по всем предметам:", top_student, "со средним баллом", top_student_score)


Самый высокий средний балл по предмету: Балл по ОБЖ с баллом 78.33333333333333
Ученик, который больше других преуспевает по всем предметам: Петров со средним баллом 77.33333333333333
