<a href="https://colab.research.google.com/github/loppi-ru/0315/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B8_%D0%90%D1%85%D0%BC%D0%B0%D1%82%D0%BE%D0%B2%D0%B0%D0%9C%D0%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Практика 2

задание 1

In [30]:
a = 5
b = 8
c = a * b / 2
print (c)

20.0


задание 2

In [29]:
N = 456

s = N // 100
d = (N // 10) % 10
e = N % 10

print("Сотни:", s)
print("Десятки:", d)
print("Единицы:", e)

Сотни: 4
Десятки: 5
Единицы: 6


задание 3

In [28]:
n = 3665
hours = n // 3600
minutes = (n % 3600) // 60
seconds = n % 60

print ("Сейчас {hours:02}:{minutes:02}:{seconds:02}")

Сейчас {hours:02}:{minutes:02}:{seconds:02}


Практика 3

задание 1

In [27]:
input = "абв, абвг, вбгд, абд"
parts = input.split(", ")
lengths = [len(part) for part in parts]
print(",".join(map(str, lengths)))

3,4,4,3


задание 2

In [26]:
stroka = "Привет, мир"
n = 8
m = 5
import re

мир = re.findall(r'\b\w+\b', stroka)

first_part_limit = min(n, len(stroka))
first_part_string = stroka[:first_part_limit]
first_part = re.findall(r'\b\w+\b', first_part_string)
second_part_string = stroka[m:]
second_part = re.findall(r'\b\w+\b', second_part_string)
print(first_part)
print(second_part)

['Привет']
['т', 'мир']


Практика 4

задание 1

In [1]:
b = int(input())
match b:
  case 400:
    print("Неправильный запрос")
  case 401:
    print("Unauthorized")
  case 402:
    print("Payment Required")
  case 403:
    print("Forbidden")
  case 404:
    print("NotFound")
  case 405:
    print("Method Not Allowed")
  case _:
    print("Other")

500
Other


задание 2

In [2]:
a = int(input())
b = int(input())
if (a > 0 and b > 0):
  print("Точка в первой четверти")
if (a < 0 and b > 0):
  print("Точка во второй четверти")
if (a < 0 and b < 0):
  print("Точка в третьей четверти")
if (a > 0 and b < 0):
  print("Точка в четвертой четверти")

50
100
Точка в первой четверти


задание 3

In [3]:
b = int(input("Введите год:"))
if (b % 4 != 0):
  print("Год не является високосным")

elif (b % 100 == 0 and b % 400 == 0):
  print("Год является високосным")
else:
  print("Год является високосным")

Введите год:2024
Год является високосным


Практика 5

задание 1

In [4]:
n = int(input("Введите начальное число n: "))
m = int(input("Введите конечное число m: "))

suma = sum(range(n, m + 1))

print(f"Сумма чисел от {n} до {m} равна {suma}.")


Введите начальное число n: 10
Введите конечное число m: 20
Сумма чисел от 10 до 20 равна 165.


задание 2

In [5]:
while True:
    n = float(input("Первое число n: "))
    m = float(input("Второе число m: "))
    if n == m:
        print("Ввели одинаковые числа")
        break
    suma = n + m
    print(f"Сумма {n} и {m} равна {suma}.")

Первое число n: 10
Второе число m: 20
Сумма 10.0 и 20.0 равна 30.0.
Первое число n: 10
Второе число m: 10
Ввели одинаковые числа


Практика 6

задание 1

In [11]:
numbers = []
squares = []
cubes = []

for i in range(1, 11):
    numbers.append(i)
    squares.append(i ** 2)
    cubes.append(i ** 3)

print("Числа:", numbers)
print("Квадраты:", squares)
print("Кубы:", cubes)

Числа: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Квадраты: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Кубы: [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


задание 2

In [12]:
numbers = []
while True:
    num = int(input("Введите число (0 для завершения): "))
    if num == 0:
        break
    numbers.append(num)

if numbers:
    min_value = min(numbers)
    max_value = max(numbers)
    sorted_asc = sorted(numbers)
    sorted_desc = sorted(numbers, reverse=True)
    count_elements = len(numbers)
    count_ones = numbers.count(1)
    sum_numbers = sum(numbers)
    last_index = len(numbers) - 1
    last_value = numbers[last_index]

    print("Минимальное значение:", min_value)
    print("Максимальное значение:", max_value)
    print("Отсортированный по возрастанию список:", sorted_asc)
    print("Отсортированный по убыванию список:", sorted_desc)
    print("Количество элементов в списке:", count_elements)
    print("Количество единиц в списке:", count_ones)
    print("Сумма всех чисел:", sum_numbers)
    print("Индекс последнего введенного элемента:", last_index)
    print("Значение последнего введенного элемента:", last_value)
else:
    print("Список пуст.")

Введите число (0 для завершения): 2
Введите число (0 для завершения): 7
Введите число (0 для завершения): 0
Минимальное значение: 2
Максимальное значение: 7
Отсортированный по возрастанию список: [2, 7]
Отсортированный по убыванию список: [7, 2]
Количество элементов в списке: 2
Количество единиц в списке: 0
Сумма всех чисел: 9
Индекс последнего введенного элемента: 1
Значение последнего введенного элемента: 7


задание 3

In [15]:
numbers = []
while True:
    num = int(input("Введите число (0 для завершения): "))
    if num == 0:
        break
    if num % 2 == 0:
        numbers.append(num)

numbers = [num for num in numbers if num % 10 != 0]

print("Итоговый список:", numbers)

Введите число (0 для завершения): 2
Введите число (0 для завершения): 5
Введите число (0 для завершения): 10
Введите число (0 для завершения): 0
Итоговый список: [2]


Практика 7

задание 1

In [16]:
import numpy as np

n = int(input("Введите размер матрицы n: "))

matrix = np.arange(1, n*n + 1).reshape(n, n)

print("Полученная матрица:")
print(matrix)

determinant = np.linalg.det(matrix)

print("Определитель матрицы:", determinant)

Введите размер матрицы n: 4
Полученная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Определитель матрицы: 0.0


задание 2

In [17]:
import pandas as pd

data = {
    'ФИО': ['Петров', 'Иванов', 'Сидорова'],
    'Балл по программированию': [78, 56, 81],
    'Балл по ОБЖ': [93, 67, 75],
    'Балл по алгебре': [61, 73, 70]
}

df = pd.DataFrame(data)

average_scores = df[['Балл по программированию', 'Балл по ОБЖ', 'Балл по алгебре']].mean()

highest_avg_subject = average_scores.idxmax()
highest_avg_score = average_scores.max()

df['Средний балл'] = df[['Балл по программированию', 'Балл по ОБЖ', 'Балл по алгебре']].mean(axis=1)
top_student = df.loc[df['Средний балл'].idxmax(), 'ФИО']
top_student_score = df['Средний балл'].max()

print("Самый высокий средний балл по предмету:", highest_avg_subject, "с баллом", highest_avg_score)
print("Ученик, который больше других преуспевает по всем предметам:", top_student, "со средним баллом", top_student_score)

Самый высокий средний балл по предмету: Балл по ОБЖ с баллом 78.33333333333333
Ученик, который больше других преуспевает по всем предметам: Петров со средним баллом 77.33333333333333


Практика 9

задание 1

In [18]:
numbers = []
count_dict = {}

while True:
    num = int(input("Введите число (0 для завершения): "))
    if num == 0:
        break
    numbers.append(num)
for number in numbers:
    if number in count_dict:
        count_dict[number] += 1
    else:
        count_dict[number] = 1

unique_numbers = list(count_dict.keys())

print("Словарь с количеством вхождений:", count_dict)
print("Список уникальных чисел:", unique_numbers)

Введите число (0 для завершения): 7
Введите число (0 для завершения): 9
Введите число (0 для завершения): 12
Введите число (0 для завершения): 0
Словарь с количеством вхождений: {7: 1, 9: 1, 12: 1}
Список уникальных чисел: [7, 9, 12]


задание 2

In [23]:
phone_book = {}

def add_entry():
    name = input("Введите имя: ")
    phone_number = input("Введите номер: ")
    phone_book[name] = phone_number
    print(f'Добавлена запись "{name}": "{phone_number}"')

def get_number():
    name = input("Введите имя: ")
    if name in phone_book:
        print(f'Номер телефона для "{name}": "{phone_book[name]}"')
    else:
        print(f'Запись для "{name}" не найдена.')

command = input("Введите add чтобы добавить или who чтобы узнать: ")
if command == "add":
    add_entry()
elif command == "who":
    get_number()
else:
    print("Неверная команда. Пожалуйста, введите 'add' или 'who'.")


Введите add чтобы добавить или who чтобы узнать: add
Введите имя: madina
Введите номер: +79000606955
Добавлена запись "madina": "+79000606955"


Практика 10

задание 1

In [24]:
def sum_numbers():
    total = 0
    while True:
        number = int(input("Введите число (для завершения введите 0): "))
        if number == 0:
            break
        total += number
    return total

result = sum_numbers()
print(f'Сумма всех введенных чисел: {result}')

Введите число (для завершения введите 0): 15
Введите число (для завершения введите 0): 67
Введите число (для завершения введите 0): 0
Сумма всех введенных чисел: 82


задание 2

In [25]:
def input_contacts():
    contacts = {}
    while True:
        name = input("Введите имя (введите 0 для завершения): ")
        phone = input("Введите номер телефона (введите 0 для завершения): ")

        if name == '0' and phone == '0':
            break

        contacts[name] = phone
    return contacts

def get_sorted_phones(contacts):
    return sorted(contacts.values())

def get_sorted_names(contacts):
    return sorted(contacts.keys())

contacts = input_contacts()

sorted_phones = get_sorted_phones(contacts)
sorted_names = get_sorted_names(contacts)

print("Номера телефонов в порядке возрастания:", sorted_phones)
print("Имена в порядке возрастания:", sorted_names)

Введите имя (введите 0 для завершения): мадина
Введите номер телефона (введите 0 для завершения): +79000606955
Введите имя (введите 0 для завершения): варя
Введите номер телефона (введите 0 для завершения): +79958406955
Введите имя (введите 0 для завершения): 0
Введите номер телефона (введите 0 для завершения): 0
Номера телефонов в порядке возрастания: ['+79000606955', '+79958406955']
Имена в порядке возрастания: ['варя', 'мадина']
